# This is a basic workflow to help you get started with Actions

name: 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 push:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    docker:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - run: docker run web
      - run: docker build -t 8f7cbbcb394fac624a377bb2421ebc7e6c2c8e14823aea73845c517d437b232a
